IF OBJECT_ID ( 'dbo.TranspNeilRatingTable', 'P' ) IS NOT NULL   
    DROP PROCEDURE dbo.TranspNeilRatingTable;  
GO  
CREATE PROCEDURE dbo.TranspNeilRatingTable
AS  
    INSERT dbo.clratings(
         BroadcastDate, 
         MarketBreak, 
         TCastStartTime, 
         TCastDaypart, 
         TCastName, 
         ProgramID, 
         TCastID, 
         TCastOriginator, 
         TCastOriginatorID, 
         TCastOriginatorType, 
         TCastStandardType, 
         TCastExpandedType, 
         TCastSpecialFlag, 
         TCastBreakoutFlag, 
         TCastCoverageArea, 
         TCastTrackageName, 
         TCastEpisodeTitle, 
         TCastLiveFlag, 
         TCastComplexFlag, 
         TCastGAAFlag, 
         TCastGappedFlag, 
         TCastLongTermFlag, 
         TCastMultiDayFlag, 
         TCastPremeireFlag, 
         TCastRepeatsFlag, 
         TCastLessThan5Flag, 
         TCastOriginalAcquired, 
         TCastDuration, 
         TCastCommercialDuration, 
         RatingBase, 
         TCastIntabCount, 
         HUTPUT, 
         ComplexDuration, 
         ShareDenominator, 
         UniverseEstimate, 
         UEType, 
         CoverageAreaUE, 
         PlayDelayLabel, 
         HHWeightedViewing, 
         HHWeightedCommercialViewing, 
         HHProjection, 
         HHNCCMProjection, 
         HHPUT, 
         HHUE, 
         F25WeightedViewing, 
         F25WeightedCommercialViewing, 
         F25Projection, 
         F25NCCMProjection, 
         F25PUT, 
         F25UE, 
         M25WeightedViewing, 
         M25WeightedCommercialViewing, 
         M25Projection, 
         M25NCCMProjection, 
         M25PUT, 
         M25UE, 
         F68WeightedViewing, 
         F68WeightedCommercialViewing, 
         F68Projection, 
         F68NCCMProjection, 
         F68PUT, 
         F68UE, 
         M68WeightedViewing, 
         M68WeightedCommercialViewing, 
         M68Projection, 
         M68NCCMProjection, 
         M68PUT, 
         M68UE, 
         F911WeightedViewing, 
         F911WeightedCommercialViewing, 
         F911Projection, 
         F911NCCMProjection, 
         F911PUT, 
         F911UE, 
         M911WeightedViewing, 
         M911WeightedCommercialViewing, 
         M911Projection, 
         M911NCCMProjection, 
         M911PUT, 
         M911UE, 
         F1224WeightedViewing, 
         F1224WeightedCommercialViewing, 
         F1224Projection, 
         F1224NCCMProjection, 
         F1224PUT, 
         F1224UE, 
         M1224WeightedViewing, 
         M1224WeightedCommercialViewing, 
         M1224Projection, 
         M1224NCCMProjection, 
         M1224PUT, 
         M1224UE, 
         F1517WeightedViewing, 
         F1517WeightedCommercialViewing, 
         F1517Projection, 
         F1517NCCMProjection, 
         F1517PUT, 
         F1517UE, 
         M1517WeightedViewing, 
         M1517WeightedCommercialViewing, 
         M1517Projection, 
         M1517NCCMProjection, 
         M1517PUT, 
         M1517UE, 
         F1820WeightedViewing, 
         F1820WeightedCommercialViewing, 
         F1820Projection, 
         F1820NCCMProjection, 
         F1820PUT, 
         F1820UE, 
         M1820WeightedViewing, 
         M1820WeightedCommercialViewing, 
         M1820Projection, 
         M1820NCCMProjection, 
         M1820PUT, 
         M1820UE, 
         F2124WeightedViewing, 
         F2124WeightedCommercialViewing, 
         F2124Projection, 
         F2124NCCMProjection, 
         F2124PUT, 
         F2124UE, 
         M2124WeightedViewing, 
         M2124WeightedCommercialViewing, 
         M2124Projection, 
         M2124NCCMProjection, 
         M2124PUT, 
         M2124UE, 
         F2529WeightedViewing, 
         F2529WeightedCommercialViewing, 
         F2529Projection, 
         F2529NCCMProjection, 
         F2529PUT, 
         F2529UE, 
         M2529WeightedViewing, 
         M2529WeightedCommercialViewing, 
         M2529Projection, 
         M2529NCCMProjection, 
         M2529PUT, 
         M2529UE, 
         F3034WeightedViewing, 
         F3034WeightedCommercialViewing, 
         F3034Projection, 
         F3034NCCMProjection, 
         F3034PUT, 
         F3034UE, 
         M3034WeightedViewing, 
         M3034WeightedCommercialViewing, 
         M3034Projection, 
         M3034NCCMProjection, 
         M3034PUT, 
         M3034UE, 
         F3539WeightedViewing, 
         F3539WeightedCommercialViewing, 
         F3539Projection, 
         F3539NCCMProjection, 
         F3539PUT, 
         F3539UE, 
         M3539WeightedViewing, 
         M3539WeightedCommercialViewing, 
         M3539Projection, 
         M3539NCCMProjection, 
         M3539PUT, 
         M3539UE, 
         F4044WeightedViewing, 
         F4044WeightedCommercialViewing, 
         F4044Projection, 
         F4044NCCMProjection, 
         F4044PUT, 
         F4044UE, 
         M4044WeightedViewing, 
         M4044WeightedCommercialViewing, 
         M4044Projection, 
         M4044NCCMProjection, 
         M4044PUT, 
         M4044UE, 
         F4549WeightedViewing, 
         F4549WeightedCommercialViewing, 
         F4549Projection, 
         F4549NCCMProjection, 
         F4549PUT, 
         F4549UE, 
         M4549WeightedViewing, 
         M4549WeightedCommercialViewing, 
         M4549Projection, 
         M4549NCCMProjection, 
         M4549PUT, 
         M4549UE, 
         F5054WeightedViewing, 
         F5054WeightedCommercialViewing, 
         F5054Projection, 
         F5054NCCMProjection, 
         F5054PUT, 
         F5054UE, 
         M5054WeightedViewing, 
         M5054WeightedCommercialViewing, 
         M5054Projection, 
         M5054NCCMProjection, 
         M5054PUT, 
         M5054UE, 
         F5559WeightedViewing, 
         F5559WeightedCommercialViewing, 
         F5559Projection, 
         F5559NCCMProjection, 
         F5559PUT, 
         F5559UE, 
         M5559WeightedViewing, 
         M5559WeightedCommercialViewing, 
         M5559Projection, 
         M5559NCCMProjection, 
         M5559PUT, 
         M5559UE, 
         F6064WeightedViewing, 
         F6064WeightedCommercialViewing, 
         F6064Projection, 
         F6064NCCMProjection, 
         F6064PUT, 
         F6064UE, 
         M6064WeightedViewing, 
         M6064WeightedCommercialViewing, 
         M6064Projection, 
         M6064NCCMProjection, 
         M6064PUT, 
         M6064UE, 
         F6599WeightedViewing, 
         F6599WeightedCommercialViewing, 
         F6599Projection, 
         F6599NCCMProjection, 
         F6599PUT, 
         F6599UE, 
         M6599WeightedViewing, 
         M6599WeightedCommercialViewing, 
         M6599Projection, 
         M6599NCCMProjection, 
         M6599PUT, 
         M6599UE)

         SELECT 
            temp.BroadcastDate, 
            temp.MarketBreak, 
            temp.TCastStartTime, 
            temp.TCastDaypart AS TCastDaypart, 
            temp.TCastName AS TCastName, 
            temp.ProgramID AS ProgramID, 
            temp.TCastID AS TCastID, 
            temp.TCastOriginator, 
            temp.TCastOriginatorID AS TCastOriginatorID, 
            temp.TCastOriginatorType AS TCastOriginatorType, 
            temp.TCastStandardType AS TCastStandardType, 
            temp.TCastExpandedType AS TCastExpandedType, 
            temp.TCastSpecialFlag AS TCastSpecialFlag, 
            temp.TCastBreakoutFlag AS TCastBreakoutFlag, 
            temp.TCastCoverageArea AS TCastCoverageArea, 
            temp.TCastTrackageName AS TCastTrackageName, 
            temp.TCastEpisodeTitle AS TCastEpisodeTitle, 
            temp.TCastLiveFlag AS TCastLiveFlag, 
            temp.TCastComplexFlag AS TCastComplexFlag, 
            temp.TCastGAAFlag AS TCastGAAFlag, 
            temp.TCastGappedFlag AS TCastGappedFlag, 
            temp.TCastLongTermFlag AS TCastLongTermFlag, 
            temp.TCastMultiDayFlag AS TCastMultiDayFlag, 
            temp.TCastPremeireFlag AS TCastPremeireFlag, 
            temp.TCastRepeatsFlag AS TCastRepeatsFlag, 
            temp.TCastLessThan5Flag AS TCastLessThan5Flag, 
            temp.TCastOriginalAcquired AS TCastOriginalAcquired, 
            temp.TCastDuration AS TCastDuration, 
            temp.TCastCommercialDuration AS TCastCommercialDuration, 
            temp.RatingBase AS RatingBase, 
            temp.TCastIntabCount AS TCastIntabCount, 
            temp.HUTPUT AS HUTPUT, 
            temp.ComplexDuration AS ComplexDuration, 
            temp.ShareDenominator AS ShareDenominator, 
            temp.UniverseEstimate AS UniverseEstimate, 
            temp.UEType AS UEType, 
            temp.CoverageAreaUE AS CoverageAreaUE, 
            temp.PlayDelayLabel, 
            MAX(CASE WHEN Demographic = 'Household' THEN TCastWeightedViewing END) HHWeightedViewing,
			MAX(CASE WHEN Demographic = 'Household' THEN TCastWeightedCommercialViewing END) HHWeightedCommercialViewing,
			MAX(CASE WHEN Demographic = 'Household' THEN Projection END) HHProjection,
       MAX(CASE WHEN Demographic = 'Household' THEN NCCMProjection END) HHNCCMProjection,
       MAX(CASE WHEN Demographic = 'Household' THEN HUTPUT END) HHPUT,
       MAX(CASE WHEN Demographic = 'Household' THEN UniverseEstimate END) HHUE,
       MAX(CASE WHEN Demographic = 'Females 2 - 5' THEN TCastWeightedViewing END) F25WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 2 - 5' THEN TCastWeightedCommercialViewing END) F25WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 2 - 5' THEN Projection END) F25Projection,
       MAX(CASE WHEN Demographic = 'Females 2 - 5' THEN NCCMProjection END) F25NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 2 - 5' THEN HUTPUT END) F25PUT,
       MAX(CASE WHEN Demographic = 'Females 2 - 5' THEN UniverseEstimate END) F25UE,
       MAX(CASE WHEN Demographic = 'Males 2 - 5' THEN TCastWeightedViewing END) M25WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 2 - 5' THEN TCastWeightedCommercialViewing END) M25WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 2 - 5' THEN Projection END) M25Projection,
       MAX(CASE WHEN Demographic = 'Males 2 - 5' THEN NCCMProjection END) M25NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 2 - 5' THEN HUTPUT END) M25PUT,
       MAX(CASE WHEN Demographic = 'Males 2 - 5' THEN UniverseEstimate END) M25UE,
       MAX(CASE WHEN Demographic = 'Females 6 - 8' THEN TCastWeightedViewing END) F68WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 6 - 8' THEN TCastWeightedCommercialViewing END) F68WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 6 - 8' THEN Projection END) F68Projection,
       MAX(CASE WHEN Demographic = 'Females 6 - 8' THEN NCCMProjection END) F68NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 6 - 8' THEN HUTPUT END) F68PUT,
       MAX(CASE WHEN Demographic = 'Females 6 - 8' THEN UniverseEstimate END) F68UE,
       MAX(CASE WHEN Demographic = 'Males 6 - 8' THEN TCastWeightedViewing END) M68WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 6 - 8' THEN TCastWeightedCommercialViewing END) M68WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 6 - 8' THEN Projection END) M68Projection,
       MAX(CASE WHEN Demographic = 'Males 6 - 8' THEN NCCMProjection END) M68NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 6 - 8' THEN HUTPUT END) M68PUT,
       MAX(CASE WHEN Demographic = 'Males 6 - 8' THEN UniverseEstimate END) M68UE,
       MAX(CASE WHEN Demographic = 'Females 9 - 11' THEN TCastWeightedViewing END) F911WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 9 - 11' THEN TCastWeightedCommercialViewing END) F911WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 9 - 11' THEN Projection END) F911Projection,
       MAX(CASE WHEN Demographic = 'Females 9 - 11' THEN NCCMProjection END) F911NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 9 - 11' THEN HUTPUT END) F911PUT,
       MAX(CASE WHEN Demographic = 'Females 9 - 11' THEN UniverseEstimate END) F911UE,
       MAX(CASE WHEN Demographic = 'Males 9 - 11' THEN TCastWeightedViewing END) M911WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 9 - 11' THEN TCastWeightedCommercialViewing END) M911WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 9 - 11' THEN Projection END) M911Projection,
       MAX(CASE WHEN Demographic = 'Males 9 - 11' THEN NCCMProjection END) M911NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 9 - 11' THEN HUTPUT END) M911PUT,
       MAX(CASE WHEN Demographic = 'Males 9 - 11' THEN UniverseEstimate END) M911UE,
       MAX(CASE WHEN Demographic = 'Females 12 - 14' THEN TCastWeightedViewing END) F1224WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 12 - 14' THEN TCastWeightedCommercialViewing END) F1224WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 12 - 14' THEN Projection END) F1224Projection,
       MAX(CASE WHEN Demographic = 'Females 12 - 14' THEN NCCMProjection END) F1224NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 12 - 14' THEN HUTPUT END) F1224PUT,
       MAX(CASE WHEN Demographic = 'Females 12 - 14' THEN UniverseEstimate END) F1224UE,
       MAX(CASE WHEN Demographic = 'Males 12 - 14' THEN TCastWeightedViewing END) M1224WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 12 - 14' THEN TCastWeightedCommercialViewing END) M1224WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 12 - 14' THEN Projection END) M1224Projection,
       MAX(CASE WHEN Demographic = 'Males 12 - 14' THEN NCCMProjection END) M1224NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 12 - 14' THEN HUTPUT END) M1224PUT,
       MAX(CASE WHEN Demographic = 'Males 12 - 14' THEN UniverseEstimate END) M1224UE,
       MAX(CASE WHEN Demographic = 'Females 15 - 17' THEN TCastWeightedViewing END) F1517WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 15 - 17' THEN TCastWeightedCommercialViewing END) F1517WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 15 - 17' THEN Projection END) F1517Projection,
       MAX(CASE WHEN Demographic = 'Females 15 - 17' THEN NCCMProjection END) F1517NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 15 - 17' THEN HUTPUT END) F1517PUT,
       MAX(CASE WHEN Demographic = 'Females 15 - 17' THEN UniverseEstimate END) F1517UE,
       MAX(CASE WHEN Demographic = 'Males 15 - 17' THEN TCastWeightedViewing END) M1517WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 15 - 17' THEN TCastWeightedCommercialViewing END) M1517WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 15 - 17' THEN Projection END) M1517Projection,
       MAX(CASE WHEN Demographic = 'Males 15 - 17' THEN NCCMProjection END) M1517NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 15 - 17' THEN HUTPUT END) M1517PUT,
       MAX(CASE WHEN Demographic = 'Males 15 - 17' THEN UniverseEstimate END) M1517UE,
       MAX(CASE WHEN Demographic = 'Females 18 - 20' THEN TCastWeightedViewing END) F1820WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 18 - 20' THEN TCastWeightedCommercialViewing END) F1820WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 18 - 20' THEN Projection END) F1820Projection,
       MAX(CASE WHEN Demographic = 'Females 18 - 20' THEN NCCMProjection END) F1820NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 18 - 20' THEN HUTPUT END) F1820PUT,
       MAX(CASE WHEN Demographic = 'Females 18 - 20' THEN UniverseEstimate END) F1820UE,
       MAX(CASE WHEN Demographic = 'Males 18 - 20' THEN TCastWeightedViewing END) M1820WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 18 - 20' THEN TCastWeightedCommercialViewing END) M1820WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 18 - 20' THEN Projection END) M1820Projection,
       MAX(CASE WHEN Demographic = 'Males 18 - 20' THEN NCCMProjection END) M1820NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 18 - 20' THEN HUTPUT END) M1820PUT,
       MAX(CASE WHEN Demographic = 'Males 18 - 20' THEN UniverseEstimate END) M1820UE,
       MAX(CASE WHEN Demographic = 'Females 21 - 24' THEN TCastWeightedViewing END) F2124WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 21 - 24' THEN TCastWeightedCommercialViewing END) F2124WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 21 - 24' THEN Projection END) F2124Projection,
       MAX(CASE WHEN Demographic = 'Females 21 - 24' THEN NCCMProjection END) F2124NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 21 - 24' THEN HUTPUT END) F2124PUT,
       MAX(CASE WHEN Demographic = 'Females 21 - 24' THEN UniverseEstimate END) F2124UE,
       MAX(CASE WHEN Demographic = 'Males 21 - 24' THEN TCastWeightedViewing END) M2124WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 21 - 24' THEN TCastWeightedCommercialViewing END) M2124WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 21 - 24' THEN Projection END) M2124Projection,
       MAX(CASE WHEN Demographic = 'Males 21 - 24' THEN NCCMProjection END) M2124NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 21 - 24' THEN HUTPUT END) M2124PUT,
       MAX(CASE WHEN Demographic = 'Males 21 - 24' THEN UniverseEstimate END) M2124UE,
       MAX(CASE WHEN Demographic = 'Females 25 - 29' THEN TCastWeightedViewing END) F2529WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 25 - 29' THEN TCastWeightedCommercialViewing END) F2529WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 25 - 29' THEN Projection END) F2529Projection,
       MAX(CASE WHEN Demographic = 'Females 25 - 29' THEN NCCMProjection END) F2529NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 25 - 29' THEN HUTPUT END) F2529PUT,
       MAX(CASE WHEN Demographic = 'Females 25 - 29' THEN UniverseEstimate END) F2529UE,
       MAX(CASE WHEN Demographic = 'Males 25 - 29' THEN TCastWeightedViewing END) M2529WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 25 - 29' THEN TCastWeightedCommercialViewing END) M2529WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 25 - 29' THEN Projection END) M2529Projection,
       MAX(CASE WHEN Demographic = 'Males 25 - 29' THEN NCCMProjection END) M2529NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 25 - 29' THEN HUTPUT END) M2529PUT,
       MAX(CASE WHEN Demographic = 'Males 25 - 29' THEN UniverseEstimate END) M2529UE,
       MAX(CASE WHEN Demographic = 'Females 30 - 34' THEN TCastWeightedViewing END) F3034WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 30 - 34' THEN TCastWeightedCommercialViewing END) F3034WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 30 - 34' THEN Projection END) F3034Projection,
       MAX(CASE WHEN Demographic = 'Females 30 - 34' THEN NCCMProjection END) F3034NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 30 - 34' THEN HUTPUT END) F3034PUT,
       MAX(CASE WHEN Demographic = 'Females 30 - 34' THEN UniverseEstimate END) F3034UE,
       MAX(CASE WHEN Demographic = 'Males 30 - 34' THEN TCastWeightedViewing END) M3034WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 30 - 34' THEN TCastWeightedCommercialViewing END) M3034WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 30 - 34' THEN Projection END) M3034Projection,
       MAX(CASE WHEN Demographic = 'Males 30 - 34' THEN NCCMProjection END) M3034NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 30 - 34' THEN HUTPUT END) M3034PUT,
       MAX(CASE WHEN Demographic = 'Males 30 - 34' THEN UniverseEstimate END) M3034UE,
       MAX(CASE WHEN Demographic = 'Females 35 - 39' THEN TCastWeightedViewing END) F3539WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 35 - 39' THEN TCastWeightedCommercialViewing END) F3539WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 35 - 39' THEN Projection END) F3539Projection,
       MAX(CASE WHEN Demographic = 'Females 35 - 39' THEN NCCMProjection END) F3539NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 35 - 39' THEN HUTPUT END) F3539PUT,
       MAX(CASE WHEN Demographic = 'Females 35 - 39' THEN UniverseEstimate END) F3539UE,
       MAX(CASE WHEN Demographic = 'Males 35 - 39' THEN TCastWeightedViewing END) M3539WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 35 - 39' THEN TCastWeightedCommercialViewing END) M3539WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 35 - 39' THEN Projection END) M3539Projection,
       MAX(CASE WHEN Demographic = 'Males 35 - 39' THEN NCCMProjection END) M3539NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 35 - 39' THEN HUTPUT END) M3539PUT,
       MAX(CASE WHEN Demographic = 'Males 35 - 39' THEN UniverseEstimate END) M3539UE,
       MAX(CASE WHEN Demographic = 'Females 40 - 44' THEN TCastWeightedViewing END) F4044WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 40 - 44' THEN TCastWeightedCommercialViewing END) F4044WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 40 - 44' THEN Projection END) F4044Projection,
       MAX(CASE WHEN Demographic = 'Females 40 - 44' THEN NCCMProjection END) F4044NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 40 - 44' THEN HUTPUT END) F4044PUT,
       MAX(CASE WHEN Demographic = 'Females 40 - 44' THEN UniverseEstimate END) F4044UE,
       MAX(CASE WHEN Demographic = 'Males 40 - 44' THEN TCastWeightedViewing END) M4044WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 40 - 44' THEN TCastWeightedCommercialViewing END) M4044WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 40 - 44' THEN Projection END) M4044Projection,
       MAX(CASE WHEN Demographic = 'Males 40 - 44' THEN NCCMProjection END) M4044NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 40 - 44' THEN HUTPUT END) M4044PUT,
       MAX(CASE WHEN Demographic = 'Males 40 - 44' THEN UniverseEstimate END) M4044UE,
       MAX(CASE WHEN Demographic = 'Females 45 - 49' THEN TCastWeightedViewing END) F4549WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 45 - 49' THEN TCastWeightedCommercialViewing END) F4549WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 45 - 49' THEN Projection END) F4549Projection,
       MAX(CASE WHEN Demographic = 'Females 45 - 49' THEN NCCMProjection END) F4549NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 45 - 49' THEN HUTPUT END) F4549PUT,
       MAX(CASE WHEN Demographic = 'Females 45 - 49' THEN UniverseEstimate END) F4549UE,
       MAX(CASE WHEN Demographic = 'Males 45 - 49' THEN TCastWeightedViewing END) M4549WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 45 - 49' THEN TCastWeightedCommercialViewing END) M4549WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 45 - 49' THEN Projection END) M4549Projection,
       MAX(CASE WHEN Demographic = 'Males 45 - 49' THEN NCCMProjection END) M4549NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 45 - 49' THEN HUTPUT END) M4549PUT,
       MAX(CASE WHEN Demographic = 'Males 45 - 49' THEN UniverseEstimate END) M4549UE,
       MAX(CASE WHEN Demographic = 'Females 50 - 54' THEN TCastWeightedViewing END) F5054WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 50 - 54' THEN TCastWeightedCommercialViewing END) F5054WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 50 - 54' THEN Projection END) F5054Projection,
       MAX(CASE WHEN Demographic = 'Females 50 - 54' THEN NCCMProjection END) F5054NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 50 - 54' THEN HUTPUT END) F5054PUT,
       MAX(CASE WHEN Demographic = 'Females 50 - 54' THEN UniverseEstimate END) F5054UE,
       MAX(CASE WHEN Demographic = 'Males 50 - 54' THEN TCastWeightedViewing END) M5054WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 50 - 54' THEN TCastWeightedCommercialViewing END) M5054WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 50 - 54' THEN Projection END) M5054Projection,
       MAX(CASE WHEN Demographic = 'Males 50 - 54' THEN NCCMProjection END) M5054NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 50 - 54' THEN HUTPUT END) M5054PUT,
       MAX(CASE WHEN Demographic = 'Males 50 - 54' THEN UniverseEstimate END) M5054UE,
       MAX(CASE WHEN Demographic = 'Females 55 - 59' THEN TCastWeightedViewing END) F5559WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 55 - 59' THEN TCastWeightedCommercialViewing END) F5559WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 55 - 59' THEN Projection END) F5559Projection,
       MAX(CASE WHEN Demographic = 'Females 55 - 59' THEN NCCMProjection END) F5559NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 55 - 59' THEN HUTPUT END) F5559PUT,
       MAX(CASE WHEN Demographic = 'Females 55 - 59' THEN UniverseEstimate END) F5559UE,
       MAX(CASE WHEN Demographic = 'Males 55 - 59' THEN TCastWeightedViewing END) M5559WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 55 - 59' THEN TCastWeightedCommercialViewing END) M5559WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 55 - 59' THEN Projection END) M5559Projection,
       MAX(CASE WHEN Demographic = 'Males 55 - 59' THEN NCCMProjection END) M5559NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 55 - 59' THEN HUTPUT END) M5559PUT,
       MAX(CASE WHEN Demographic = 'Males 55 - 59' THEN UniverseEstimate END) M5559UE,
       MAX(CASE WHEN Demographic = 'Females 60 - 64' THEN TCastWeightedViewing END) F6064WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 60 - 64' THEN TCastWeightedCommercialViewing END) F6064WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 60 - 64' THEN Projection END) F6064Projection,
       MAX(CASE WHEN Demographic = 'Females 60 - 64' THEN NCCMProjection END) F6064NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 60 - 64' THEN HUTPUT END) F6064PUT,
       MAX(CASE WHEN Demographic = 'Females 60 - 64' THEN UniverseEstimate END) F6064UE,
       MAX(CASE WHEN Demographic = 'Males 60 - 64' THEN TCastWeightedViewing END) M6064WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 60 - 64' THEN TCastWeightedCommercialViewing END) M6064WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 60 - 64' THEN Projection END) M6064Projection,
       MAX(CASE WHEN Demographic = 'Males 60 - 64' THEN NCCMProjection END) M6064NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 60 - 64' THEN HUTPUT END) M6064PUT,
       MAX(CASE WHEN Demographic = 'Males 60 - 64' THEN UniverseEstimate END) M6064UE,
       MAX(CASE WHEN Demographic = 'Females 65 - 99' THEN TCastWeightedViewing END) F6599WeightedViewing,
       MAX(CASE WHEN Demographic = 'Females 65 - 99' THEN TCastWeightedCommercialViewing END) F6599WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Females 65 - 99' THEN Projection END) F6599Projection,
       MAX(CASE WHEN Demographic = 'Females 65 - 99' THEN NCCMProjection END) F6599NCCMProjection,
       MAX(CASE WHEN Demographic = 'Females 65 - 99' THEN HUTPUT END) F6599PUT,
       MAX(CASE WHEN Demographic = 'Females 65 - 99' THEN UniverseEstimate END) F6599UE,
       MAX(CASE WHEN Demographic = 'Males 65 - 99' THEN TCastWeightedViewing END) M6599WeightedViewing,
       MAX(CASE WHEN Demographic = 'Males 65 - 99' THEN TCastWeightedCommercialViewing END) M6599WeightedCommercialViewing,
       MAX(CASE WHEN Demographic = 'Males 65 - 99' THEN Projection END) M6599Projection,
       MAX(CASE WHEN Demographic = 'Males 65 - 99' THEN NCCMProjection END) M6599NCCMProjection,
       MAX(CASE WHEN Demographic = 'Males 65 - 99' THEN HUTPUT END) M6599PUT,
       MAX(CASE WHEN Demographic = 'Males 65 - 99' THEN UniverseEstimate END) M6599UE
         FROM dbo.temp
         GROUP BY 
            temp.MarketBreak, 
            temp.BroadcastDate, 
            temp.TCastStartTime, 
            temp.TCastOriginator, 
            temp.PlayDelayLabel
            ORDER BY temp.BroadcastDate ASC, temp.TCastOriginator ASC, temp.TCastStartTime ASC

      DELETE 
      FROM dbo.temp
GO  